package io.github.kuddev.pebrel.mobile.session

import android.content.Context
import android.graphics.Typeface

/**
 * The application font registry. Asset names are generated by the Android
 * packaging task and are kept here so every terminal surface resolves the same
 * family from the same canonical preference value.
 */
object TerminalFonts {
    const val MAPLE_ASSET = "terminal.ttf"
    const val JETBRAINS_ASSET = "fonts/JetBrainsMono-Regular.ttf"
    const val SYSTEM_FONT = TerminalPreferenceValues.SYSTEM_FONT

    data class Option(val id: String, val assetPath: String?)

    val options: List<Option> = listOf(
        Option(TerminalPreferenceValues.MAPLE_FONT, MAPLE_ASSET),
        Option(TerminalPreferenceValues.JETBRAINS_FONT, JETBRAINS_ASSET),
        Option(SYSTEM_FONT, null),
    )

    private val cache = mutableMapOf<String, Typeface>()

    @Synchronized
    fun typeface(context: Context, family: String): Typeface {
        val canonical = when (family) {
            TerminalPreferenceValues.JETBRAINS_FONT -> TerminalPreferenceValues.JETBRAINS_FONT
            TerminalPreferenceValues.SYSTEM_FONT -> TerminalPreferenceValues.SYSTEM_FONT
            else -> TerminalPreferenceValues.MAPLE_FONT
        }
        cache[canonical]?.let { return it }
        val asset = options.first { it.id == canonical }.assetPath
        val loaded = asset?.let { Typeface.createFromAsset(context.applicationContext.assets, it) }
            ?: Typeface.MONOSPACE
        cache[canonical] = loaded
        return loaded
    }
}
